server:
  port: 8081
spring:
  application:
    name: ad-search
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://182.254.181.205:3306?imooc_ad_data?autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12321312
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  cloud:
    nacos:
      discovery:
        server-addr: 182.254.181.205:8848
adconf:
  mysql:
    host: 182.254.181.205
    port: 3306
    username: root
    password: 123124321
    binlogName: binlog.000038
    position: 60451