server:
  port: 9000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 182.254.181.205:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ad-sponor
          uri: lb://ad-sponor
          predicates:
          - Path=/ad-sponsor/**
  application:
    name: ad-gateway