server:
  port: 8001
  servlet:
    context-path: /ad-sponsor
spring:
  application:
    name: ad-sponsor
  cloud:
    nacos:
      discovery:
        server-addr: 182.254.181.205:8848
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      # 格式化sql语句
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://182.254.181.205:3306/imooc_ad_data?autoReconnect=true
    username: root
    password: 123213123123
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
